RogerCreasy/ChassisPHP

composer.json, composer.lock, index.php, lib/Framework/Core.php, lib/Framework/Router.php
this is just a start, for proof of concept.
Our router class needs to be fleshed out.
=> extend phrouter with our own router

index.php, lib/Framework/Core.php
we need to expand on this...
Again, it is working, good for proof of concept
=> add rudimentary 404 check

index.php, lib/Framework/Core.php
=> refactor dispatch method to run

Http/Controllers/HomeController.php, Http/Controllers/NameController.php, composer.json, lib/Framework/Core.php, routes/frontend.php
add route variable handling to controller
=> Feature fastroute

Http/Middleware/Middleware.php
This is just a beginning, only the framework of a middleware class
=> write framework of middelware class

composer.json, composer.lock, lib/Framework/helpers.php
Use the Symfony Dumper to better handle mixed values and objects when debugging values.
=> Use the Symfony Dumper (#71)

.gitignore, storage/sessions/.gitignore
Committing this to make the directory available to other contributors
=> WIP: add storage directory structure. 

README.md
i'm update your readme and add something :)
=> add message how to clone from github

.env.example, lib/Framework/Container.php, lib/Framework/EnvVarsLoader.php, public/index.php
I want to resolve #92 by move session timeout to environment variables (.evn file)
=> Move session timeout to .env file

cli-config.php
fixed a bug that crept in with one of our changes. Calls to the CLI were failing.
=> change Connection.php location in cli-config.php

CONTRIBUTING.md
Hi,
I made the changes we discussed in contributing document.
=> Changes made as discussed

lib/Framework/Hash.php
A simple Hash class to make one-way password hash and to check that a string matches a hash (#105)
The class can be augmented with more functionalities if needed.
It uses standard php functions [password_hash](http://php.net/manual/en/function.password-hash.php) and [password_verify](http://php.net/manual/en/function.password-verify.php)
PS: @RogerCreasy you might want to add to your composer.json and in your README that PHP **7.1** is required in order to install/run this framework.
=> Hashing functions (ref #105)

CONTRIBUTORS.md
Do I have to include myself in it? #108 
Messed up the 1st PR. This one should be correct
=> Updated CONTRIBUTORS.md to add new contributors

CONTRIBUTORS.md
Added myself to it as you said. #109 #108
=> Updated CONTRIBUTORS.md again

lib/Framework/Container.php, lib/Framework/Core.php
=> remove unnecessary use statements

Http/Controllers/Backend/UserController.php, Http/Middleware/TestMiddleware.php, app/ServiceProviders/UserControllerServiceProvider.php, lib/Framework/Container.php, lib/Framework/Http/Controller.php, lib/Framework/Http/MiddlewareQueue.php, lib/Framework/Router.php
This addition still needs some work. It is functional, but should be cleaned up.
=> add middleware queue class; add middleware functionality

lib/Framework/Container.php, lib/Framework/Http/Middleware/SessionMiddleware.php, lib/Framework/Http/MiddlewareQueue.php, lib/Framework/Router.php
also WIP: testing  middleware to start session on every page
=> improve router access to request

app/Http/Controllers/Backend/UserController.php, app/Http/Controllers/NameController.php, app/Http/Middleware/TestMiddleware.php, lib/Framework/Http/Middleware/ControllerMiddleware.php, lib/Framework/Http/MiddlewareQueue.php, lib/Framework/Router.php, routes/backend.php, routes/frontend.php
put middleware in an array in the correct order; 
then, add each as callable to an SplDopublyLinkedList object for processing
=> change middleware strategy; 

app/Http/Controllers/AboutController.php, app/Http/Controllers/Backend/ContentController.php, lib/Framework/Container.php, resources/views/frontend/pages/about.twig.php, routes/frontend.php
This PR also has part of the twig var dump for testing added, but not activated.
=> add about page and controller; add Entity connection to controller

Database/Entities/Content.php, Database/Entities/User.php, app/Http/Controllers/Backend/ContentController.php, resources/views/backend/pages/content.twig.php
Also, the inverse requirements to User
remove some unused code
clean up some spacing issues
=> add foreign keys for author and updatedBy to content entity

Database/Entities/Gallery.php, Database/Entities/Image.php
=> add gallery constructor; rename Images to Image

Database/Entities/Gallery.php
=> add getters/setters to Gallery entity

Database/Entities/Album.php
=> rename Entity Gallery as Album

app/Http/Controllers/Backend/ImageController.php, resources/views/backend/pages/imageForm.twig.php, resources/views/backend/pages/images.twig.php
=> add file management functionality

Database/Entities/Album.php, Database/Entities/Image.php, Database/Entities/User.php, app/Http/Controllers/Backend/ImageController.php, lib/Framework/Core.php, resources/views/backend/pages/imageForm.twig.php, resources/views/backend/pages/images.twig.php, routes/backend.php
=> update imageController to manage Album relationship

app/Http/Controllers/Backend/ImageController.php
this PR also adds the ability to delete images
=> add PSR2 line length fixes

app/Http/Controllers/Backend/ContentController.php, app/Http/Controllers/HomeController.php, phpcs.xml
HomeController, Backend ContentController; 
added phpcs.xml file
=> PSR2 fixes: 

composer.json, composer.lock
Installed and ran phpunit for first time - failed at tests requiring guzzlehttp
=> added guzzle dependency

Config/app.php, lib/Database/Connection.php, lib/Framework/Config.php, lib/Framework/ConfigManager.php, lib/Framework/Container.php, public/index.php
**Solves Issue #327** 
This should make working with configuation variables a lot easier.
* `class Config` is now called `class ConfigManager`
* `public static function get()` is used to retrieve config values through dot-notation
* Singleton Pattern for Config Manager
=> Issue327 - Refactor Working with Config Variables

lib/Framework/Http/Middleware/AuthMiddleware.php, lib/Framework/helpers.php
=> add checkAuth() helper function

resources/views/backend/pages/forgot.twig.php
=> set cancel button to redirect to backend/login

resources/views/errors/error.html, routes/frontend.php
=> add error twig template; add route to error

lib/Framework/Container.php, resources/views/errors/404.html, resources/views/errors/404.twig, routes/frontend.php
=> use twig template for 404 page

app/Http/Controllers/Backend/UserController.php
=> reorder use statements in UserController

README.md
=> change php requirement in readme

composer.json, composer.lock, lib/Framework/Container/ControllerServiceProvider.php
Also, change controller service provider to use renamed league container method
=> update league container

app/Http/Controllers/Backend/UserController.php
add conditional check; alert message for self delete attempt
=> Prevent self-delete

lib/Framework/Container.php, lib/Framework/ServiceProviders/RequestServiceProvider.php, lib/Framework/ServiceProviders/ResponseServiceProvider.php
=> move framework service providers into framework structure
